export const MY_APPLICATIONS_REQUEST = "MY_APPLICATIONS_REQUEST";
export const MY_APPLICATIONS_SUCCESS = "MY_APPLICATIONS_SUCCESS";
export const MY_APPLICATIONS_FAIL = "MY_APPLICATIONS_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS";