export const ALL_JOB_REQUEST = "ALL_JOB_REQUEST";
export const ALL_JOB_SUCCESS = "ALL_JOB_SUCCESS";
export const ALL_JOB_FAIL = "ALL_JOB_FAIL";

export const ADMIN_JOB_REQUEST = "ADMIN_JOB_REQUEST";
export const ADMIN_JOB_SUCCESS = "ADMIN_JOB_SUCCESS";
export const ADMIN_JOB_FAIL = "ADMIN_JOB_FAIL";

export const COMPANY_JOB_REQUEST = "COMPANY_JOB_REQUEST";
export const COMPANY_JOB_SUCCESS = "COMPANY_JOB_SUCCESS";
export const COMPANY_JOB_FAIL = "COMPANY_JOB_FAIL";

export const NEW_JOB_REQUEST = "NEW_JOB_REQUEST";
export const NEW_JOB_SUCCESS = "NEW_JOB_SUCCESS";
export const NEW_JOB_FAIL = "NEW_JOB_FAIL";
export const NEW_JOB_RESET = "NEW_JOB_RESET";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";