export const ALL_JOB_REQUEST = "ALL_JOB_REQUEST";
export const ALL_JOB_SUCCESS = "ALL_JOB_SUCCESS";
export const ALL_JOB_FAIL = "ALL_JOB_FAIL";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";